package agent

// The SSH server, in Go, replacing OpenSSH inside the agent image.
//
// Why replace something that works: sshd is what forced the rest of the agent's
// shape, and every bit of that shape is a cost.
//
//   - plug-agent is setuid root ONLY because sshd runs it as the unprivileged
//     `plug` user while it needs the docker socket or the pod's SA token. A Go
//     server IS the process that holds those, so the setuid bit goes away - on
//     the most exposed binary of the product.
//   - nineteen lines of sshd_config generated by `echo` in the Dockerfile, two
//     Unix users, two ForceCommands, and an `apk add openssh-server` that
//     already needed a three-attempt retry because it has failed builds before.
//   - the host key stops being regenerated at every start. On its own that
//     changes NOTHING, and this comment must not pretend otherwise: the CLI
//     re-pins whatever answers (transport.go:456), so nothing is verified
//     either way, which is also why every install command carries
//     StrictHostKeyChecking=no. It matters only as the place the key will live
//     once the three missing pieces exist TOGETHER: an identity surviving pod
//     recreation, a CLI that REFUSES a change instead of noting it, and a way
//     to learn the fingerprint other than by connecting.
//
// What it must reproduce is short and fully enumerated - the sshd_config this
// replaces is in agent/Dockerfile:
//
//	user `plug`  publickey only; direct-tcpip anywhere (PermitOpen any);
//	             exec restricted to the verbs (ForceCommand); remote forwards
//	             binding 0.0.0.0 on request (GatewayPorts clientspecified);
//	             keepalive so a dead tunnel frees its binds in ~90s.
//	user `get`   no authentication at all; exec restricted to serving binaries;
//	             no forwarding of any kind.
//
// Steps 1 to 3 are here: accept, authenticate, exec, plus both forwarding
// primitives. What remains before the switch-over is the keepalive tuning, a
// host key that survives POD recreation (a file in the container only survives
// a process restart), and the image change itself. Until then this server is
// wired nowhere and sshd still serves.
//
// The exec runs the SAME binary sshd runs today, as a subprocess with
// SSH_ORIGINAL_COMMAND set. Deliberately: it keeps the 3100 lines of verbs
// untouched, so this server can be compared against sshd behaviour for
// behaviour before anything else moves. Turning those verbs into an importable
// package is what Meerkat needs, and it is a different piece of work.

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"golang.org/x/crypto/ssh"
)

// The two accounts, named as sshd names them so the CLI needs no change: it
// dials `plug` for the tunnel and `get` for downloads, and does not care what
// answers.
const (
	tunnelUser   = "plug"
	downloadUser = "get"
)

// parseAuthorizedKeys reads an authorized_keys file, skipping blanks and
// comments. A malformed line is an error rather than a silent skip: a typo that
// drops the only key would otherwise lock everyone out quietly.
func parseAuthorizedKeys(b []byte) ([]ssh.PublicKey, error) {
	var out []ssh.PublicKey
	for rest := b; len(rest) > 0; {
		key, _, _, next, err := ssh.ParseAuthorizedKey(rest)
		if err != nil {
			if len(out) > 0 && strings.TrimSpace(string(rest)) == "" {
				break
			}
			return nil, fmt.Errorf("authorized_keys: %w", err)
		}
		out = append(out, key)
		rest = next
	}
	if len(out) == 0 {
		return nil, errors.New("authorized_keys: no key in it")
	}
	return out, nil
}

// sshServer is the whole configuration. execFor is injected so the tests can
// run without the real binaries, and so the two accounts keep the strict
// separation sshd gave them through ForceCommand.
type sshServer struct {
	host    Host
	hostKey ssh.Signer
	execFor func(user string) []string // argv for this account's ForceCommand
	logf    func(string, ...any)
	verbEnv []string // embedder decisions the verb subprocess cannot ask for
	// noDownloadAccount closes the anonymous `get` account entirely.
	noDownloadAccount bool
	idleEvry          time.Duration // keepalive period; 0 disables (tests)
	// grace bounds the HANDSHAKE only. 0 means handshakeGrace; the tests shorten
	// it, since waiting a minute to prove a silent peer is dropped is not a test.
	grace time.Duration

	wg sync.WaitGroup

	// Live connections, so shutdown can end them. Closing the listener only
	// stops NEW ones: without this, stopping waits for the last developer to
	// disconnect, which for a gateway restarting means waiting on someone who
	// left a session open and went to lunch.
	mu    sync.Mutex
	conns map[*ssh.ServerConn]struct{}

	// Delivery of Served/Unserved to the Host: one goroutine, started on the
	// first event, so callbacks keep their order and a slow Host backs up its
	// own queue instead of a developer's session. See nameevents.go.
	evOnce sync.Once
	ev     chan func()
}

// track registers a live connection, returning the function that forgets it.
func (s *sshServer) track(c *ssh.ServerConn) func() {
	s.mu.Lock()
	if s.conns == nil {
		s.conns = map[*ssh.ServerConn]struct{}{}
	}
	s.conns[c] = struct{}{}
	s.mu.Unlock()
	return func() {
		s.mu.Lock()
		delete(s.conns, c)
		s.mu.Unlock()
	}
}

// CloseConnections ends every live session. Called on shutdown, after the
// listener is closed, so Serve can return instead of waiting on peers that have
// no reason to leave.
func (s *sshServer) CloseConnections() {
	s.mu.Lock()
	live := make([]*ssh.ServerConn, 0, len(s.conns))
	for c := range s.conns {
		live = append(live, c)
	}
	s.mu.Unlock()
	for _, c := range live {
		_ = c.Close()
	}
}

func (s *sshServer) note(format string, a ...any) {
	if s.logf != nil {
		s.logf(format, a...)
	}
}

// hostKeySigner loads the host key, creating it once if absent.
//
// What this buys today: nothing, and saying otherwise would be worse than
// saying nothing. A container recreated from the image has no file, so it
// generates a fresh identity, exactly as `ssh-keygen -A` did before it. And a
// stable key would still protect nothing while the CLI re-pins whatever
// answers. This is where the key will live when that changes, not evidence
// that anything is checked.
//
// The 0600 mode in a root-only directory is worth having regardless: whoever
// can replace this file can impersonate the agent to any client that HAS
// pinned it.
func hostKeySigner(path string) (ssh.Signer, error) {
	if b, err := os.ReadFile(path); err == nil {
		return ssh.ParsePrivateKey(b)
	} else if !os.IsNotExist(err) {
		return nil, err
	}
	_, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return nil, err
	}
	der, err := ssh.MarshalPrivateKey(priv, "")
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return nil, err
	}
	if err := os.WriteFile(path, pem.EncodeToMemory(der), 0o600); err != nil {
		return nil, err
	}
	return ssh.NewSignerFromKey(priv)
}

// serverConfig builds the handshake rules. The two accounts differ here and
// nowhere else, which is what sshd expressed with two `Match User` blocks.
func (s *sshServer) serverConfig() *ssh.ServerConfig {
	cfg := &ssh.ServerConfig{
		// `get` is anonymous on purpose: it serves the CLI binaries, and
		// requiring a key to download the thing that holds the key is a circle.
		// It is bounded by its ForceCommand, not by authentication.
		NoClientAuth: true,
		NoClientAuthCallback: func(c ssh.ConnMetadata) (*ssh.Permissions, error) {
			if s.noDownloadAccount {
				// The embedder closed it. Same answer as an unknown user, so the
				// port does not advertise which agents have it and which do not.
				return nil, fmt.Errorf("user %q must authenticate", c.User())
			}
			if c.User() != downloadUser {
				// Not a refusal of the connection: the client falls through to
				// publickey, which is what the tunnel user does.
				return nil, fmt.Errorf("user %q must authenticate", c.User())
			}
			return &ssh.Permissions{Extensions: map[string]string{"user": downloadUser}}, nil
		},
		PublicKeyCallback: func(c ssh.ConnMetadata, key ssh.PublicKey) (*ssh.Permissions, error) {
			if c.User() != tunnelUser {
				return nil, fmt.Errorf("user %q does not take a key", c.User())
			}
			who, ok := s.host.Verify(key)
			if !ok {
				// Fingerprint, never the key: enough to recognise a legitimate
				// client that was never enrolled, useless to an attacker.
				return nil, fmt.Errorf("key %s is not authorized", ssh.FingerprintSHA256(key))
			}
			return &ssh.Permissions{Extensions: map[string]string{
				"user": tunnelUser,
				"who":  who,
			}}, nil
		},
		ServerVersion: "SSH-2.0-plug",
	}
	cfg.AddHostKey(s.hostKey)
	return cfg
}

// Serve accepts until ln is closed, then waits for live connections to finish.
// What sshd gave this port for free, and what had to be written back.
//
// handshakeGrace is LoginGraceTime: a peer that opens a connection and never
// finishes the key exchange held a goroutine, a socket and a slot forever. It
// covers the HANDSHAKE only and is cleared the moment that succeeds, or a slow
// `install` download over a bad link would die halfway through.
//
// maxHandshakes is MaxStartups, counted the way sshd counts it: connections that
// have not authenticated yet. An established session does not hold a slot, so a
// busy team is never turned away; what is bounded is how many strangers can be
// mid-handshake at once. Generous for a dev cluster, finite against a port
// somebody points a scanner at.
const (
	handshakeGrace = 60 * time.Second
	maxHandshakes  = 64
)

func (s *sshServer) Serve(ln net.Listener) error {
	gate := make(chan struct{}, maxHandshakes)
	for {
		nc, err := ln.Accept()
		if err != nil {
			s.wg.Wait()
			return err
		}
		select {
		case gate <- struct{}{}:
		default:
			// Refused rather than queued: queueing turns a flood into a backlog
			// that outlives it, and the client's own dial timeout would have
			// given up long before its turn came.
			s.note("ssh: %d handshakes already in flight, refusing %s", maxHandshakes, nc.RemoteAddr())
			nc.Close()
			continue
		}
		s.wg.Add(1)
		go func() {
			defer s.wg.Done()
			s.handle(nc, func() { <-gate })
		}()
	}
}

// absorb returns a deferred recover for one unit of work.
//
// A recover only catches panics in ITS OWN goroutine, and handle spawns four:
// the keepalive, the global requests, every session and every direct-tcpip.
// Guarding handle alone left all of them uncovered, which is where the work
// actually happens - a test that panicked inside a session took the whole test
// binary down and said so.
func (s *sshServer) absorb(what string, onPanic func()) func() {
	return func() {
		if r := recover(); r != nil {
			s.note("ssh: %s panicked: %v", what, r)
			if onPanic != nil {
				onPanic()
			}
		}
	}
}

func (s *sshServer) handle(nc net.Conn, releaseSlot func()) {
	// One connection's panic must not take the agent with it. Everything below
	// parses what a stranger sent; sshd answered for that with a process per
	// connection, and this is one goroutine among many inside a gateway that has
	// other work to do.
	defer s.absorb("connection from "+nc.RemoteAddr().String(), func() { nc.Close() })()
	grace := s.grace
	if grace == 0 {
		grace = handshakeGrace
	}
	_ = nc.SetDeadline(time.Now().Add(grace))
	conn, chans, reqs, err := ssh.NewServerConn(nc, s.serverConfig())
	// The slot is held for the HANDSHAKE, not the session: what is bounded is
	// how many unauthenticated peers can be in flight at once.
	releaseSlot()
	if err != nil {
		// Includes every rejected key and every scanner. Worth a line, not an
		// alarm: this port is reachable by design.
		s.note("ssh: handshake from %s failed: %v", nc.RemoteAddr(), err)
		nc.Close()
		return
	}
	// The grace is over: from here the deadline would kill a legitimate idle
	// session, and a long download is exactly that.
	_ = nc.SetDeadline(time.Time{})
	defer conn.Close()
	defer s.track(conn)()

	user := conn.Permissions.Extensions["user"]
	// Who the Host says this key belongs to, empty when the key authenticates
	// the SOFTWARE rather than a person (see Host.Verify). It rides into the
	// verbs as PLUG_WHO and into every name event.
	who := conn.Permissions.Extensions["who"]
	if s.idleEvry > 0 {
		// What ClientAliveInterval/CountMax did: notice a dead peer so its
		// remote-forward binds free up before a reconnecting session tries to
		// re-arm them. Three misses, same as the config it replaces.
		go func() { defer s.absorb("keepalive", nil)(); s.keepalive(conn) }()
	}

	// Remote forwards belong to THIS connection: whatever it opened must be
	// closed when it ends, or a crashed session leaves a port bound and the next
	// one cannot re-arm the name. sshd freed them by owning the process; here it
	// is explicit.
	fwd := &forwardSet{conn: conn, srv: s}
	defer fwd.closeAll()
	// Same event, said to the Host: whatever this connection was serving, it is
	// not serving it any more. Deferred beside closeAll because it is the same
	// fact about the same failure modes.
	defer s.withdrawAll(fwd)

	go func() { defer s.absorb("global requests", nil)(); s.globalRequests(reqs, user, fwd) }()

	for nch := range chans {
		switch nch.ChannelType() {
		case "session":
			go func(nch ssh.NewChannel) {
				defer s.absorb("session", nil)()
				s.session(nch, user, who, fwd, conn.RemoteAddr(), conn.LocalAddr())
			}(nch)
		case "direct-tcpip":
			// The outbound half of the tunnel. `get` never gets it: that account
			// downloads binaries and nothing else (AllowTcpForwarding no).
			if user != tunnelUser {
				_ = nch.Reject(ssh.Prohibited, "this account may not forward")
				continue
			}
			go func(nch ssh.NewChannel) { defer s.absorb("direct-tcpip", nil)(); s.directTCPIP(nch) }(nch)
		default:
			_ = nch.Reject(ssh.UnknownChannelType, "unsupported channel type")
		}
	}
}

// directTCPIP opens the connection the client asked for, FROM INSIDE the
// cluster, and splices it onto the channel. This is the whole forward datapath:
// `plug curl http://api:8080` becomes one of these.
//
// The name is resolved here, by the container's own resolver, which is the
// point of the product: the caller gets the cluster's view of DNS without
// joining the cluster.
func (s *sshServer) directTCPIP(nch ssh.NewChannel) {
	var req struct {
		Host       string
		Port       uint32
		OriginHost string
		OriginPort uint32
	}
	if err := ssh.Unmarshal(nch.ExtraData(), &req); err != nil {
		_ = nch.Reject(ssh.ConnectionFailed, "malformed direct-tcpip request")
		return
	}
	addr := net.JoinHostPort(req.Host, fmt.Sprint(req.Port))

	// Bounded: an unresolvable name must come back as an error the CLI can
	// report, not as a channel that hangs until the user gives up. The CLI's own
	// budget is 10s (channelTimeout), so stay under it and let the refusal
	// carry the reason.
	conn, err := net.DialTimeout("tcp", addr, dialBudget)
	if err != nil {
		_ = nch.Reject(ssh.ConnectionFailed, err.Error())
		return
	}
	ch, reqs, err := nch.Accept()
	if err != nil {
		conn.Close()
		return
	}
	go ssh.DiscardRequests(reqs)
	copyBoth(ch, conn)
}

// dialBudget bounds one direct-tcpip open. Under the CLI's channelTimeout (10s)
// so the refusal, which names the cause, wins the race against a bare timeout.
const dialBudget = 8 * time.Second

// globalRequests handles what arrives outside any channel: the remote forwards
// that `-s` is built on.
func (s *sshServer) globalRequests(reqs <-chan *ssh.Request, user string, fwd *forwardSet) {
	for r := range reqs {
		switch r.Type {
		case "tcpip-forward":
			if user != tunnelUser {
				if r.WantReply {
					_ = r.Reply(false, nil)
				}
				continue
			}
			port, err := fwd.open(r.Payload)
			if err != nil {
				s.note("ssh: tcpip-forward refused: %v", err)
				if r.WantReply {
					_ = r.Reply(false, nil)
				}
				continue
			}
			if r.WantReply {
				// A client that asked for port 0 reads the allocated one from
				// this reply. Getting it wrong means it exposes a port nobody
				// listens on, silently.
				_ = r.Reply(true, ssh.Marshal(struct{ Port uint32 }{port}))
			}
		case "cancel-tcpip-forward":
			ok := fwd.cancel(r.Payload)
			if r.WantReply {
				_ = r.Reply(ok, nil)
			}
		default:
			// keepalive@openssh.com among others: answering false IS the answer,
			// it proves the peer is alive.
			if r.WantReply {
				_ = r.Reply(false, nil)
			}
		}
	}
}

// forwardSet is one connection's remote forwards, keyed by the bind address the
// client named. Its whole reason to exist is closeAll: sshd released these when
// the process it owned died, and nothing releases them here unless we do.
type forwardSet struct {
	conn *ssh.ServerConn
	srv  *sshServer

	// The names this connection serves, so its teardown withdraws exactly
	// those. A name outlives the session that served it in every failure mode
	// worth handling, which is why it is tracked here and not inferred.
	heldNames

	mu  sync.Mutex
	lns map[string]net.Listener
}

type bindRequest struct {
	Addr string
	Port uint32
}

// open binds and starts pushing accepted connections to the client.
//
// The bind address is taken from the client, which is `GatewayPorts
// clientspecified`: asking for 0.0.0.0 gets 0.0.0.0. Without it sshd bound the
// loopback and the exposed port answered nobody inside the cluster, which is
// the one behaviour this must not get wrong.
func (f *forwardSet) open(payload []byte) (uint32, error) {
	var req bindRequest
	if err := ssh.Unmarshal(payload, &req); err != nil {
		return 0, fmt.Errorf("malformed tcpip-forward: %w", err)
	}
	ln, err := net.Listen("tcp", net.JoinHostPort(req.Addr, fmt.Sprint(req.Port)))
	if err != nil {
		// Port already bound: the CLI turns this refusal into "another session
		// exposes it", which is exactly what a collision means.
		return 0, err
	}
	port := uint32(ln.Addr().(*net.TCPAddr).Port)

	f.mu.Lock()
	if f.lns == nil {
		f.lns = map[string]net.Listener{}
	}
	// Keyed by what the CLIENT will cancel with: the address it named, and the
	// port it ends up with. A client that asked for 0 cancels with the allocated
	// port, per the protocol.
	f.lns[key(req.Addr, port)] = ln
	f.mu.Unlock()

	go f.serve(ln, req.Addr, port)
	return port, nil
}

func key(addr string, port uint32) string { return net.JoinHostPort(addr, fmt.Sprint(port)) }

// serve pushes each accepted connection to the client as a forwarded-tcpip
// channel. One goroutine per listener, ending when the listener closes.
func (f *forwardSet) serve(ln net.Listener, bindAddr string, bindPort uint32) {
	for {
		c, err := ln.Accept()
		if err != nil {
			return // closed by cancel or by closeAll
		}
		go f.push(c, bindAddr, bindPort)
	}
}

func (f *forwardSet) push(c net.Conn, bindAddr string, bindPort uint32) {
	origHost, origPortStr, _ := net.SplitHostPort(c.RemoteAddr().String())
	var origPort uint32
	fmt.Sscan(origPortStr, &origPort)

	payload := ssh.Marshal(struct {
		Addr       string
		Port       uint32
		OriginAddr string
		OriginPort uint32
	}{bindAddr, bindPort, origHost, origPort})

	ch, reqs, err := f.conn.OpenChannel("forwarded-tcpip", payload)
	if err != nil {
		// The client went away between accept and open. Nothing to report: its
		// side is already gone.
		c.Close()
		return
	}
	go ssh.DiscardRequests(reqs)
	copyBoth(ch, c)
}

func (f *forwardSet) cancel(payload []byte) bool {
	var req bindRequest
	if err := ssh.Unmarshal(payload, &req); err != nil {
		return false
	}
	f.mu.Lock()
	ln, ok := f.lns[key(req.Addr, req.Port)]
	delete(f.lns, key(req.Addr, req.Port))
	f.mu.Unlock()
	if !ok {
		return false
	}
	return ln.Close() == nil
}

// closeAll releases every bind this connection holds. Called when the
// connection ends, however it ends: a session killed with SIGKILL must not
// leave a port bound, or the name cannot be re-armed until the agent restarts.
func (f *forwardSet) closeAll() {
	f.mu.Lock()
	lns := f.lns
	f.lns = nil
	f.mu.Unlock()
	for _, ln := range lns {
		_ = ln.Close()
	}
}

func (s *sshServer) keepalive(conn *ssh.ServerConn) {
	t := time.NewTicker(s.idleEvry)
	defer t.Stop()
	misses := 0
	for range t.C {
		// SendRequest waits for the reply with no deadline of its own, so a peer
		// whose TCP is still up but which answers nothing blocked here forever:
		// the miss counter never moved, and the connection kept its remote
		// forwards until the agent restarted. The client side already had this
		// timeout; the server side is where a stuck peer costs a NAME.
		errc := make(chan error, 1)
		go func() {
			_, _, err := conn.SendRequest("keepalive@openssh.com", true, nil)
			errc <- err
		}()
		var err error
		select {
		case err = <-errc:
		case <-time.After(s.idleEvry):
			err = fmt.Errorf("no answer within %s", s.idleEvry)
		}
		if err == nil {
			misses = 0
			continue
		}
		if misses++; misses >= 3 {
			s.note("ssh: peer %s stopped answering, closing", conn.RemoteAddr())
			conn.Close()
			return
		}
	}
}

// session serves one session channel. Only `exec` is honoured, and only into
// this account's fixed argv: that is ForceCommand, and it is the reason neither
// account has a shell.
func (s *sshServer) session(nch ssh.NewChannel, user, who string, fwd *forwardSet, remote, local net.Addr) {
	ch, reqs, err := nch.Accept()
	if err != nil {
		return
	}
	defer ch.Close()

	for req := range reqs {
		switch req.Type {
		case "exec":
			var payload struct{ Command string }
			if err := ssh.Unmarshal(req.Payload, &payload); err != nil {
				_ = req.Reply(false, nil)
				return
			}
			_ = req.Reply(true, nil)
			s.runForced(ch, user, who, fwd, payload.Command, remote, local)
			return
		case "shell", "pty-req", "subsystem", "x11-req":
			// No shell, ever. Same answer sshd gives with ForceCommand set,
			// and the reason a stolen key cannot become a foothold.
			_ = req.Reply(false, nil)
		default:
			if req.WantReply {
				_ = req.Reply(false, nil)
			}
		}
	}
}

// runForced executes the account's command with the client's request in
// SSH_ORIGINAL_COMMAND, exactly as sshd does, and returns its exit status.
func (s *sshServer) runForced(ch ssh.Channel, user, who string, fwd *forwardSet, original string, remote, local net.Addr) {
	argv := s.execFor(user)
	if len(argv) == 0 {
		fmt.Fprintf(ch.Stderr(), "plug: no command for %q\n", user)
		sendExit(ch, 1)
		return
	}
	cmd := exec.Command(argv[0], argv[1:]...)
	// SSH_CLIENT is not decoration: the name lease records it (sessionOrigin in
	// main.go), and it is what a collision message shows to tell a colleague's
	// machine from your own. Dropping it would have emptied that message without
	// failing anything - the e2e cell only checks the refusal happens, not that
	// it names an origin.
	//
	// Same shape sshd uses, so the reader on the other side needs no change:
	// SSH_CLIENT is "<client-ip> <client-port> <server-port>", SSH_CONNECTION
	// adds the server address in the middle.
	//
	// PLUG_WHO is the identity the Host put on this key, empty when it names no
	// one. The verbs run in another process and cannot ask the Host anything, so
	// this is how `info` can answer "the agent knows you as alice" and how a
	// developer finds out their enrolled key is actually being recognised.
	cmd.Env = append(os.Environ(),
		"SSH_ORIGINAL_COMMAND="+original,
		"SSH_CLIENT="+sshClientVar(remote, local),
		"SSH_CONNECTION="+sshConnectionVar(remote, local),
		"PLUG_WHO="+who,
	)
	cmd.Env = append(cmd.Env, s.verbEnv...)
	// The verb's answer goes to the client untouched; a copy of the tail stays
	// here, because "ok" and "ok reassigned" mean different things to the Host
	// and the exit status tells them apart in neither case (answer() exits 0
	// even for an error line).
	tail := &tailWriter{max: 4096}
	cmd.Stdin = ch
	cmd.Stdout = io.MultiWriter(ch, tail)
	cmd.Stderr = ch.Stderr()

	code := 0
	if err := cmd.Run(); err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) {
			code = ee.ExitCode()
		} else {
			fmt.Fprintf(ch.Stderr(), "plug: %v\n", err)
			code = 1
		}
	}
	if code == 0 && user == tunnelUser {
		s.announce(fwd, who, original, tail.lastLine())
	}
	sendExit(ch, code)
}

// splitAddr yields host and port, tolerating an address that carries neither.
func splitAddr(a net.Addr) (string, string) {
	if a == nil {
		return "", ""
	}
	host, port, err := net.SplitHostPort(a.String())
	if err != nil {
		return a.String(), ""
	}
	return host, port
}

func sshClientVar(remote, local net.Addr) string {
	rh, rp := splitAddr(remote)
	_, lp := splitAddr(local)
	return fmt.Sprintf("%s %s %s", rh, rp, lp)
}

func sshConnectionVar(remote, local net.Addr) string {
	rh, rp := splitAddr(remote)
	lh, lp := splitAddr(local)
	return fmt.Sprintf("%s %s %s %s", rh, rp, lh, lp)
}

// sendExit reports the status and closes the write side, which is what tells
// the client the command is over. Without it a piped `ssh … install | sh` hangs
// waiting for an end that never comes.
func sendExit(ch ssh.Channel, code int) {
	_, _ = ch.SendRequest("exit-status", false, ssh.Marshal(struct{ Status uint32 }{uint32(code)}))
	_ = ch.CloseWrite()
}

// copyBoth relays a channel and a connection until either side ends, returning
// once both directions are done. Used by the forwarding primitives.
func copyBoth(a io.ReadWriteCloser, b io.ReadWriteCloser) {
	var wg sync.WaitGroup
	wg.Add(2)
	go func() { defer wg.Done(); _, _ = io.Copy(a, b); closeWrite(a) }()
	go func() { defer wg.Done(); _, _ = io.Copy(b, a); closeWrite(b) }()
	wg.Wait()
}

// closeWrite half-closes when the type allows it, so the peer sees EOF instead
// of waiting for a timeout. Falls back to a full close.
func closeWrite(c io.Closer) {
	type writeCloser interface{ CloseWrite() error }
	if wc, ok := c.(writeCloser); ok {
		_ = wc.CloseWrite()
		return
	}
	_ = c.Close()
}
